[*] Move /skel/* to / to ease tar and make

diff --git a/.local/bin/debian-purge-packages b/.local/bin/debian-purge-packages
--- a/.local/bin/debian-purge-packages
+++ b/.local/bin/debian-purge-packages
@@ -1,7 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # SPDX-License-Identifier: MIT
 #
-# Copyright (c) 2013-2018 Nicolas Iooss
+# Copyright (c) 2014-2018 Nicolas Iooss
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -21,39 +21,24 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 #
-# Convert tabs into 4-spaces in specified files (or not if -t is given),
-# strip spaces at the end of lines and replace nbsp with spaces.
+# Purge the config files of removed packages on a Debian system
 
-TAB=$'\t'
-NBSP=$'\xc2\xa0'
-
-REPLACE_TABS=true
-if [ "$1" = '-t' ]; then
-  REPLACE_TABS=false
-  shift
+# Use aptitude or apt-get
+if command -v aptitude >/dev/null; then
+    APT=aptitude
+elif command -v apt-get >/dev/null; then
+    APT=apt-get
+else
+    echo >&2 'Unable to find aptitude nor apt-get :('
+    exit 1
 fi
 
-for file in "$@"; do
-  if [ -d "$file" ]; then
-    echo >&2 "Ignoring directory $file"
-    continue
-  fi
+PKGLIST=$(dpkg -l | sed -n 's/^rc \+\([^ ]\+\).*$/\1/p')
+[ -n "$PKGLIST" ] || exit 0
 
-  # Replace tab by 4 spaces
-  if "$REPLACE_TABS" && grep -q -F "$TAB" <"$file"; then
-    echo "[tab] $file"
-    sed -i --follow-symlinks "s/$TAB/    /g" "$file"
-  fi
-
-  # End of line spaces
-  if grep -q -E " +\$" <"$file"; then
-    echo "[eol] $file"
-    sed -i --follow-symlinks "s/  *\$//" "$file"
-  fi
-
-  # Remove non-breakable spaces
-  if grep -q -F "$NBSP" <"$file"; then
-    echo "[nbsp] $file"
-    sed -i --follow-symlinks "s/$NBSP/ /g" "$file"
-  fi
-done
+echo "These packages will be removed:" "${PKGLIST}"
+if [ "$(id -u)" = "0" ]; then
+    exec "$APT" purge "${PKGLIST}"
+else
+    exec sudo "$APT" purge "${PKGLIST}"
+fi
